services:
  worker:
    develop:
      watch:
        - action: sync+restart
          path: ./src/opentlawpy
          target: /app/src/opentlawpy
        - action: rebuild
          path: ./pyproject.toml

  listener:
    develop:
      watch:
        - action: sync+restart
          path: ./src/opentlawpy
          target: /app/src/opentlawpy
        - action: rebuild
          path: ./pyproject.toml
